### ISSUE TITLE
How is this supposed to be used in a Node project?

### ISSUE THREAD

**Issue by hokster7** [dziamid/parse-mock#1]
Thanks for putting this together.

I would like to test Parse Cloud code functions by mocking all queries (in effect, mocking all data). I don't particularly want this to run in a browser — I'd like to run this in node.

How am I supposed to require `parse-mock`?

I tried:

``` js
var Parse = require('parse');
require('parse-mock');
```

and I get

```
     TypeError: Cannot call method 'stubQueryFind' of undefined
```

**Comment by hokster7** [comment]
Okay, I've sort of figured out that you could just assign that mock object anywhere, so I ended up with:

``` js
var Parse = require('parse').Parse;
Parse.Mock = require('parse-mock');
```

I've also found that:

``` js
var Parse = require('parse').Parse;
require('parse-mock');
```

... both work. Which one would you recommend?

**Comment by dziamid** [comment]
I'd suggest you use `Parse.Mock` namespace to stay consistent in both node and browser testing in case may want to you that with jasmine for example.

**Comment by hokster7** [comment]
Great thanks @dziamid.
